package jsx

var (
	Head  = T("head")
	Body  = T("body")
	Meta  = T("meta")
	Style = T("style")
	Div   = T("div")
	Span  = T("span")
	A     = T("a")
	Img   = T("img")
	Table = T("table")
	Thead = T("thead")
	Tbody = T("tbody")
	Th    = T("th")
	Tr    = T("tr")
	Td    = T("td")
	Ul    = T("ul")
	Li    = T("li")
)
