package genshindb

// https://bbs.nga.cn/read.php?tid=27859119
var Recommends = RecommendSet{
	// 火
	"可莉": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"安柏": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"宵宫": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL_HURT,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"托马": {},
	"烟绯": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"班尼特": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_HP_PERCENT, FIGHT_PROP_HEAL_ADD,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_HP_PERCENT,
	},
	"胡桃": {
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"辛焱": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_PHYSICAL_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_DEFENSE_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"迪卢克": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL_HURT,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"香菱": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_FIRE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	// 雷
	"丽莎": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEC_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"九条裟罗": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ELEC_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"刻晴": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEC_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"北斗": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ELEC_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"菲谢尔": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEC_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"雷泽": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_PHYSICAL_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"雷电将军": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	// 水
	"珊瑚宫心海": {
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_WATER_ADD_HURT, FIGHT_PROP_HEAL_ADD,
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"芭芭拉": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_HP_PERCENT, FIGHT_PROP_HEAL_ADD,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_HP_PERCENT,
	},
	"莫娜": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"行秋": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_WATER_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"达达利亚": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_WATER_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	// 冰
	"七七": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_HEAL_ADD,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT,
	},
	"优菈": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_PHYSICAL_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"凯亚": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ICE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"埃洛伊": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ICE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"甘雨": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ICE_ADD_HURT, FIGHT_PROP_CRITICAL_HURT,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"神里绫华": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ICE_ADD_HURT, FIGHT_PROP_CRITICAL_HURT,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"罗莎莉亚": {
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ICE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"迪奥娜": {
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_HP_PERCENT, FIGHT_PROP_HP_PERCENT,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_HP_PERCENT,
	},
	"重云": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ICE_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT, FIGHT_PROP_ELEMENT_MASTERY,
	},
	// 风
	"早柚": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_HEAL_ADD,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_ATTACK_PERCENT,
	},
	"枫原万叶": {
		FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_ELEMENT_MASTERY,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"温迪": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_WIND_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"琴": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_WIND_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"砂糖": {
		FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_ELEMENT_MASTERY, FIGHT_PROP_ELEMENT_MASTERY,
		FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_ELEMENT_MASTERY,
	},
	"魈": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_WIND_ADD_HURT, FIGHT_PROP_CRITICAL_HURT,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	// 岩
	"凝光": {
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_ROCK_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_ATTACK_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"诺艾尔": {
		FIGHT_PROP_DEFENSE_PERCENT, FIGHT_PROP_ROCK_ADD_HURT, FIGHT_PROP_CRITICAL,
		FIGHT_PROP_DEFENSE_PERCENT, FIGHT_PROP_CHARGE_EFFICIENCY, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
	"钟离": {
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_HP_PERCENT, FIGHT_PROP_HP_PERCENT,
		FIGHT_PROP_HP_PERCENT, FIGHT_PROP_CHARGE_EFFICIENCY,
	},
	"阿贝多": {
		FIGHT_PROP_DEFENSE_PERCENT, FIGHT_PROP_ROCK_ADD_HURT, FIGHT_PROP_DEFENSE_PERCENT,
		FIGHT_PROP_DEFENSE_PERCENT, FIGHT_PROP_CRITICAL, FIGHT_PROP_CRITICAL_HURT,
	},
}
